#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Moviestar.Droid.Resource", IsApplication=true)]

namespace Moviestar.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int menu_array = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cover = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int emptystar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fullstar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int star = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int ScrollLayout = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int ScrollLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05001a
			public const int ScrollLayout2 = 2131034138;
			
			// aapt resource value: 0x7f050006
			public const int button1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int button2 = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int duration = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int editText1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int editText2 = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int headerLayout = 2131034120;
			
			// aapt resource value: 0x7f050017
			public const int moviePageActors = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int moviePageCover = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int moviePageDirector = 2131034136;
			
			// aapt resource value: 0x7f050016
			public const int moviePageGenre = 2131034134;
			
			// aapt resource value: 0x7f05000e
			public const int moviePageRating = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int moviePageTitle = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int rate1 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int rate2 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int rate3 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int rate4 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int rate5 = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int rateMovie = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int relativeLayout2 = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int searchBar = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int spinner = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView2 = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MovieList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MoviePage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Search = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
